=== adjit/resources-2/essentialXML/dvd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT library (dvd+)>
<!ELEMENT dvd (title, format, genre)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ATTLIST dvd id CDATA #REQUIRED>

=== adjit/resources-2/htmlXmlTutorial/xml-examples/dvd-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "dvd.dtd">
<library>
  <dvd id="1">
	 <title>Gone with the Wind</title>
	 <format>Movie</format>
	 <genre>Classic</genre>
  </dvd>
  <dvd id="2"><br/>
	 <title>Star Trek</title>
	 <format>TV Series</format>
	 <genre>Science fiction</genre>
  </dvd>
</library>
